# Rishit, Maheshwaran, Srihari 
INSERT INTO raw_data (bid, title, author, category, book_status, category_id, shelf_id, author_id, transaction_id, Student_Name, Student_ID, major, age, Issued_Date)
VALUES
(1, 'Steve Jobs', 'Walter Issacson', 'Biography', 'issued', 1, 1, 15, 7, 'Alexander Lewis', 7, 'Data Science', 26, '2024-03-19'),
(2, 'Discovery of India', 'Jawaharlal Nehru', 'History', 'issued', 2, 2, 27, 10, 'Mark Taylor', 10, 'Arts', 25, '2023-12-10'),
(3, 'My Experiments with Truth', 'Mahatma Gandhi', 'Autobiography', 'issued', 3, 1, 5, 1, 'John Doe', 1, 'Arts', 18, '2024-03-18'),
(4, 'Object Oriented Programming with C++', 'E Balagurusamy', 'Education', 'issued', 4, 2, 35, 12, 'Ava Garcia', 12, 'Law', 19, '2024-01-05'),
(5, 'Thinking with type', 'Ellen Lupton', 'Arts', 'issued', 5, 2, 54, 14, 'Jude Bellingham', 14, 'Math', 19, '2024-03-11'),
(6, 'The Photographer''s', 'Lindsay Adler', 'Photography', 'issued', 6, 4, 7, 3, 'Sophia Diaz', 3, 'Arts', 21, '2024-01-25'),
(7, 'Think and Grow', 'Napoleon Hill', 'Economics', 'issued', 7, 3, 41, 13, 'Martin Tyler', 13, 'Medical', 26, '2024-03-25'),
(8, 'The Fifth Discipline : The Art', 'Peter M.Senge', 'Management', 'issued', 22, 3, 38, 13, 'Martin Tyler', 13, 'Medical', 26, '2024-01-05'),
(9, 'A Theory of Justice', 'John Rawls', 'Law', 'issued', 8, 3, 19, 9, 'Benjamin Murphy', 9, 'Data Science', 27, '2023-12-10'),
(10, 'Eat to Live', 'Joel Fuhrman', 'Health', 'issued', 9, 6, 45, 14, 'Jude Bellingham', 14, 'Math', 19, '2024-01-24'),
(11, 'City of Heavenly Fire', 'Cassandra Clare', 'Fiction', 'available', 10, 7, 46, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'Da Vinci Code', 'Dan Brown', 'Fiction', 'available', 10, 7, 55, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'War and Peace', 'Leo Tolstoy', 'Philosophical fiction', 'issued', 11, 5, 18, 9, 'Benjamin Murphy', 9, 'Data Science', 27, '2024-01-17'),
(14, 'Python For All', 'John Shovic', 'Education', 'available', 4, 2, 47, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'Automate The Boring Stuff With Python', 'Al Sweigart', 'Education', 'available', 4, 2, 58, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'Wings Of Fire', 'APJ Abdul Kalam', 'Autobiography', 'available', 3, 1, 52, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'Ikigai', 'Hector Garcia', 'Personal Development', 'available', 13, 6, 4, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'Who Will Cry When You Will Die', 'Robin Sharma', 'Personal Development', 'available', 13, 6, 3, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'Rich Dad Poor Dad', 'Robert T. Kiyosaki', 'Business', 'available', 14, 3, 40, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'Immortals of Meluha', 'Amish Tirpathi', 'High Fantasy', 'available', 15, 7, 56, NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'A Brief History Of Time', 'Stephen Hawking', 'SPACE', 'issued', 16, 8, 10, 5, 'Harper Lee', 5, 'Computer Science', 15, '2024-01-17'),
(22, 'I Know Why The Cage Bird Sings', 'Maya Angelou', 'Story', 'available', 17, 7, 28, NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'Lord Of Flies', 'William Golding', 'Fiction', 'issued', 10, 7, 33, 12, 'Ava Garcia', 12, 'Law', 19, '2023-12-30'),
(24, 'Lorna Doone', 'R.D. Blackmore', 'Fiction', 'issued', 10, 7, 24, 10, 'Mark Taylor', 10, 'Arts', 25, '2024-03-18'),
(25, 'Jamaica Inn', 'Daphne Du Maurier', 'Fiction', 'issued', 10, 7, 29, 11, 'Emily Brown', 11, 'Computer Science', 18, '2024-02-11'),
(26, 'Kidnapped', 'Robert Louis Stevenson', 'Fiction', 'available', 10, 7, 2, NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'Treasure Island', 'Robert Louis Stevenson', 'Fiction', 'available', 10, 7, 2, NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'The Call Of The Wild', 'Jack London', 'Fiction', 'available', 10, 7, 30, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'Charlotte''s Web', 'E.B. White', 'Fiction', 'available', 10, 7, 42, NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'The Wind In The Willows', 'Kenneth Grahame', 'Fiction', 'available', 10, 7, 22, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'Being and Time', 'Martin Heidegger', 'Philosophy', 'available', 18, 5, 20, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'The Republic', 'Plato', 'Philosophy', 'issued', 18, 5, 17, 8, 'Amelia Scott', 8, 'Arts', 26, '2024-03-19'),
(33, 'Critique of Pure Reason', 'Immanuel Kant', 'Philosophy', 'available', 18, 5, 50, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'The Prince', 'Niccolò Machiavelli', 'Philosophy', 'available', 18, 5, 25, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'Ethics', 'Baruch Spinoza', 'Philosophy', 'available', 18, 5, 51, NULL, NULL, NULL, NULL, NULL, NULL),
(36, 'Long Walk To Freedom', 'Nelson Mandela', 'Autobiography', 'available', 3, 1, 23, NULL, NULL, NULL, NULL, NULL, NULL),
(37, 'The Diary Of A Young Girl', 'Anne Frank', 'Autobiography', 'available', 3, 1, 36, NULL, NULL, NULL, NULL, NULL, NULL),
(38, 'Autobiography', 'Mark Twain', 'Autobiography', 'available', 3, 1, 48, NULL, NULL, NULL, NULL, NULL, NULL),
(39, 'Mein Kampf', 'Adolf Hitler', 'Autobiography', 'available', 3, 1, 39, NULL, NULL, NULL, NULL, NULL, NULL),
(40, 'Freakonomics', 'Steven D. Levitt and Stephen J. Dubner', 'Economics', 'issued', 7, 3, 8, 4, 'William Sanchez', 4, 'Arts', 18, '2024-02-11'),
(41, 'Thinking, Fast and Slow', 'Daniel Kahneman', 'Economics', 'available', 7, 3, 21, NULL, NULL, NULL, NULL, NULL, NULL),
(42, '23 Things They Don''t Tell You About Capitalism', 'Ha-Joon Chang', 'Economics', 'available', 7, 3, 9, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'Animal Spirits', 'George A. Akerlof and Robert J. Shiller', 'Economics', 'available', 7, 3, 31, NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'The Black Swan', 'Nassim Nicholas Taleb', 'Economics', 'issued', 7, 3, 32, 11, 'Emily Brown', 11, 'Computer Science', 18, '2024-03-06'),
(45, '1984', 'George Orwell', 'Story', 'available', 17, 7, 14, NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'The Lord Of The Rings', 'J.R.R. Tolkien', 'Story', 'issued', 17, 7, 37, 13, 'Martin Tyler', 13, 'Medical', 26, '2024-03-19'),
(47, 'The Kite Runner', 'Khaled Hosseini', 'Story', 'available', 17, 7, 34, NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'Harry Potter', 'J.K. Rowling', 'Story', 'available', 17, 7, 43, NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'The Book Thief', 'Markus Zusak', 'Story', 'available', 17, 7, 11, NULL, NULL, NULL, NULL, NULL, NULL),
(50, 'A History of the Twentieth Century', 'Martin Gilbert', 'History', 'available', 2, 2, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(51, 'Guns, Germs, and Steel', 'Jared Diamond', 'History', 'issued', 2, 2, 6, 2, 'Jane Smith', 2, 'Medical', 30, '2024-03-06'),
(52, 'A World Lit Only by Fire', 'William Manchester', 'History', 'issued', 2, 2, 12, 6, 'James Clark', 6, 'Law', 17, '2023-12-24'),
(53, 'The Crusades', 'Thomas Asbridge', 'History', 'available', 2, 2, 57, NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'Over The Edge Of The World', 'Laurence Bergreen', 'History', 'available', 2, 2, 16, NULL, NULL, NULL, NULL, NULL, NULL),
(55, 'A Beautiful Mind', 'Sylvia Nasar', 'Biography', 'available', 1, 1, 49, NULL, NULL, NULL, NULL, NULL, NULL),
(56, 'The Enigma', 'Andrew Hodges', 'Biography', 'available', 1, 1, 53, NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'Alexander Hamilton', 'Ron Chernow', 'Biography', 'available', 1, 1, 13, NULL, NULL, NULL, NULL, NULL, NULL),
(58, 'Barracoon', 'Zora Neale Hurston', 'Biography', 'available', 1, 1, 44, NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'CHURCHILL : A Life', 'Martin Gilbert', 'Biography', 'available', 1, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(60, 'A Tale of Two Cities', 'Charles Dickens', 'Historical novel', 'issued', 20, 2, 59, 14, 'Jude Bellingham', 14, 'Math', 19, '2024-01-17'),
(61, 'Les Misérables', 'Victor Hugo', 'Historical fiction', 'available', 21, 7, 26, NULL, NULL, NULL, NULL, NULL, NULL);
